name: Tests

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  tests:
    strategy:
      matrix:
        # 3.6 is missing `contextvars`.
        python: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        allow-prereleases: true
    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
    - name: Test with unittest
      run: |
        python3 -m unittest discover
